version: '2.4'
services:
  openconnect:
    image: fortiproxy:latest
    build:
      context: ./
    container_name: fortiproxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    networks:
      - openconnect
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
      - ${HTTP_PROXY_PORT}:${HTTP_PROXY_PORT}
      - 15353:53/tcp
      - 15353:53/udp
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv4.tcp_keepalive_intvl=1
      - net.ipv4.tcp_keepalive_probes=3
      - net.ipv4.tcp_keepalive_time=30  
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    healthcheck:
      test: /opt/utils/healthcheck.sh ${EXT_IP}
      timeout: 10s
      interval: 3m
      start_period: 30s
      retries: 2

networks:
  openconnect:
    name: openconnect
